In [17]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras.layers import Input, Dense 
from tensorflow.keras.models import Model 
from keras.models import Sequential
from keras.optimizers import SGD,Adam
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [18]:
path = "C:/Users/송이두/Desktop/가천대/2-1/인공지능개론/과제/data/seeds_dataset.txt"
# on_bad_lines='skip' 옵션을 추가하여 문제가 있는 줄을 건너뜁니다.
data = pd.read_csv(path, sep='\t', header=None, on_bad_lines='skip')
print("파일을 성공적으로 불러왔습니다 (문제가 있는 줄은 건너뛰었습니다).")
print(data.head())
# 몇 번째 줄이 건너뛰어졌는지 확인하려면, 원본 파일의 줄 수와 데이터프레임의 행 수를 비교해볼 수 있습니다.
print(f"데이터프레임 행 수: {len(data)}")

파일을 성공적으로 불러왔습니다 (문제가 있는 줄은 건너뛰었습니다).
       0      1       2      3      4      5      6  7
0  15.26  14.84  0.8710  5.763  3.312  2.221  5.220  1
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
2  14.29  14.09  0.9050  5.291  3.337  2.699  4.825  1
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1
데이터프레임 행 수: 199


In [3]:
data.shape

(199, 8)

In [4]:
X = data.iloc[:, :7]  # 모든 행, 0번부터 6번 열까지 선택
y = data.iloc[:, 7]   # 모든 행, 7번 열 선택 (또는 data[7] 사용)

X.shape, y.shape

((199, 7), (199,))

In [10]:
y = pd.get_dummies(y)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((159, 7), (40, 7), (159, 3), (40, 3))

## 1번 방법

#### 모델 정의

In [23]:
first = Sequential()

first.add(Dense(20, input_shape=(X_train.shape[1],), activation='relu'))
first.add(Dense(30,activation='relu'))
first.add(Dense(30,activation='relu'))
first.add(Dense(20,activation='relu'))
first.add(Dense(3, activation='softmax'))

first.compile(optimizer='Adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
first.summary()

C:\Users\송이두\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                     │ (None, 20)                  │             160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 30)                  │             630 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_22 (Dense)                     │ (None, 30)                  │             930 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_23 (Dense)                     │ (None, 20)                  │             620 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_24 (Dense)                     │ (None, 3)                   │              63 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,403 (9.39 KB)

 Trainable params: 2,403 (9.39 KB)

 Non-trainable params: 0 (0.00 B)

#### 모델 학습

In [13]:
N_EPOCHS = 30

model_history=first.fit(x=X_train, y=y_train, epochs=N_EPOCHS, batch_size=32,validation_split=0.2)
y_pred = first.predict(X_test)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 191ms/step - accuracy: 0.4094 - loss: 1.1478 - val_accuracy: 0.2500 - val_loss: 1.1675
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4274 - loss: 1.1097 - val_accuracy: 0.4062 - val_loss: 1.0386
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4146 - loss: 0.9926 - val_accuracy: 0.4062 - val_loss: 0.9833
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.3691 - loss: 1.0326 - val_accuracy: 0.7500 - val_loss: 0.9531
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6822 - loss: 0.9592 - val_accuracy: 0.7188 - val_loss: 0.9055
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6822 - loss: 0.9192 - val_accuracy: 0.7500 - val_loss: 0.8820
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6281 - loss: 0.9123 - val_accuracy: 0.7188 - val_loss: 0.8701
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6522 - loss: 0.9075 - val_accuracy: 0.7812 - val_loss: 0.8392

#### 평가

In [15]:
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.80      0.57      0.67        14
           1       0.75      0.90      0.82        10
           2       0.83      0.94      0.88        16

    accuracy                           0.80        40
   macro avg       0.79      0.80      0.79        40
weighted avg       0.80      0.80      0.79        40

[[ 8  3  3]
 [ 1  9  0]
 [ 1  0 15]]


## 2번 방법

#### 모델 정의

In [24]:
inputs = Input(shape=(X_train.shape[1],))
x = Dense(20, activation='relu')(inputs)
x = Dense(30, activation='relu')(x)
x = Dense(30, activation='relu')(x)
x = Dense(20,activation='relu')(x)
prediction = Dense(3, activation='softmax')(x)

second = Model(inputs=inputs, outputs=prediction)
second.compile(optimizer='Adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
second.summary()

Model: "functional_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)           │ (None, 7)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_25 (Dense)                     │ (None, 20)                  │             160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_26 (Dense)                     │ (None, 30)                  │             630 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_27 (Dense)                     │ (None, 30)                  │             930 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_28 (Dense)                     │ (None, 20)                  │             620 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_29 (Dense)                     │ (None, 3)                   │              63 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,403 (9.39 KB)

 Trainable params: 2,403 (9.39 KB)

 Non-trainable params: 0 (0.00 B)

#### 모델 학습

In [25]:
N_EPOCHS = 30

model_history=second.fit(x=X_train, y=y_train, epochs=N_EPOCHS, batch_size=32,validation_split=0.2)
y_pred = second.predict(X_test)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 193ms/step - accuracy: 0.2384 - loss: 1.3270 - val_accuracy: 0.3438 - val_loss: 1.1101
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.3690 - loss: 1.1015 - val_accuracy: 0.5000 - val_loss: 1.0886
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4847 - loss: 1.0673 - val_accuracy: 0.2812 - val_loss: 1.0562
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4046 - loss: 1.0441 - val_accuracy: 0.5625 - val_loss: 1.0144
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4880 - loss: 1.0137 - val_accuracy: 0.5312 - val_loss: 0.9942
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5288 - loss: 0.9935 - val_accuracy: 0.5312 - val_loss: 0.9804
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5935 - loss: 0.9725 - val_accuracy: 0.5625 - val_loss: 0.9659
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5977 - loss: 0.9507 - val_accuracy: 0.6250 - val_loss: 0.9459

#### 평가

In [26]:
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.92      0.79      0.85        14
           1       1.00      1.00      1.00        10
           2       0.83      0.94      0.88        16

    accuracy                           0.90        40
   macro avg       0.92      0.91      0.91        40
weighted avg       0.90      0.90      0.90        40

[[11  0  3]
 [ 0 10  0]
 [ 1  0 15]]


## 3번 방법

#### 모델 정의

In [34]:
class Third(Model):
    def __init__(self, num_classes):
        super(Third, self).__init__(name='third')
        self.num_classes = num_classes
        self.dense1 = Dense(20, activation='relu')
        self.dense2 = Dense(30, activation='relu')
        self.dense3 = Dense(30, activation='relu')
        self.dense4 = Dense(20, activation='relu')
        self.dense5 = Dense(num_classes, activation='softmax')
    
    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        x = self.dense3(x)
        x = self.dense4(x)
        return self.dense5(x)

third = Third(num_classes=3)
third.compile(optimizer='Adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
third.summary()

Model: "third"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_50 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_51 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_52 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_53 (Dense)                     │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_54 (Dense)                     │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

#### 모델 학습

In [40]:
N_EPOCHS = 30

model_history=third.fit(x=X_train, y=y_train, epochs=N_EPOCHS, batch_size=32,validation_split=0.2)
y_pred = third.predict(X_test)

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9331 - loss: 0.2882 - val_accuracy: 0.9688 - val_loss: 0.2315
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9268 - loss: 0.2947 - val_accuracy: 0.9688 - val_loss: 0.2347
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9342 - loss: 0.2713 - val_accuracy: 0.9688 - val_loss: 0.2324
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8883 - loss: 0.3234 - val_accuracy: 0.9688 - val_loss: 0.2247
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9446 - loss: 0.2508 - val_accuracy: 0.9688 - val_loss: 0.2197
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8914 - loss: 0.3153 - val_accuracy: 0.9688 - val_loss: 0.2132
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9279 - loss: 0.2632 - val_accuracy: 1.0000 - val_loss: 0.2121
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9289 - loss: 0.2743 - val_accuracy: 1.0000 - val_loss: 0.1982


#### 평가

In [41]:
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.85      0.79      0.81        14
           1       1.00      0.90      0.95        10
           2       0.83      0.94      0.88        16

    accuracy                           0.88        40
   macro avg       0.89      0.87      0.88        40
weighted avg       0.88      0.88      0.87        40

[[11  0  3]
 [ 1  9  0]
 [ 1  0 15]]
